"""models

Revision ID: 641b5fd44776
Revises: 
Create Date: 2023-04-01 21:28:08.039048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641b5fd44776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
