"""Name

Revision ID: a5ab4912d6ef
Revises: 1e9ecf638d2a
Create Date: 2023-04-06 00:47:43.659911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ab4912d6ef'
down_revision = '1e9ecf638d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
