"""models

Revision ID: bd23501febfa
Revises: 641b5fd44776
Create Date: 2023-04-01 21:33:23.762218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd23501febfa'
down_revision = '641b5fd44776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
